Add retry on Http error message
julienstroheker/go-cosmosdb pull request #21
Opened 2022-09-22 16:46 UTC by vineeth-thumma

2022-09-22 18:51 UTC, amanohar requested changes

2022-09-22 18:51 UTC, amanohar commented on pkg/gencosmosdb/cosmosdb/cosmosdb.go
> +		return strings.Contains(err.Error(), errorString)
A separate function should not be needed. Use a Go variadic function. 

Update `IsErrorStatusCode` to:
```Go
func IsErrorStatusCode(err error, statusCode int, errorString ...string) bool {
	if err, ok := err.(*Error); ok {
		return err.StatusCode == statusCode
	}

        if strings.Contains(err.Error(), errorString)
              return true

      return false
}
```

2022-09-22 19:05 UTC, vineeth-thumma commented on pkg/gencosmosdb/cosmosdb/cosmosdb.go
> +		return strings.Contains(err.Error(), errorString)
If we do it this way, we won't hit the below condition at all as this (`return err.StatusCode == statusCode`) will be evaluated to true/false and returned

`if strings.Contains(err.Error(), errorString) 
    return true`

2022-09-22 21:16 UTC, vineeth-thumma commented on pkg/gencosmosdb/cosmosdb/cosmosdb.go
> +		return strings.Contains(err.Error(), errorString)
we want to check the error message without relying on the error code, hence the separation

2022-09-23 15:56 UTC, amanohar commented on pkg/gencosmosdb/cosmosdb/cosmosdb.go
> +			}
Add UT

2022-09-23 16:22 UTC, jake-billings commented on example/cosmosdb/zz_generated_cosmosdb.go
>  	for i := 0; i < 5; i++ {
This is a very simple retry, and any project using this library wouldn't have much control over the retry parameters.

Have you considered using a library function that handles exponential backoff and jitters?

2022-09-23 21:24 UTC, vineeth-thumma commented on example/cosmosdb/zz_generated_cosmosdb.go
>  	for i := 0; i < 5; i++ {
yes, considered using this: https://pkg.go.dev/github.com/hashicorp/go-retryablehttp
we can enhance the existing methods and expose those parameters

2022-09-26 15:53 UTC, amanohar approved these changes

2022-09-26 16:59 UTC, vineeth-thumma commented on pkg/gencosmosdb/cosmosdb/cosmosdb.go
>  	for i := 0; i < 5; i++ {
we want the users to handle retries on a case by case basis with custom wait time, jitter, etc.
I have a backlog WI to take care of this in the next iteration, but can have those changes as part of this PR if this is blocking

2022-09-26 18:49 UTC, jake-billings commented on pkg/gencosmosdb/cosmosdb/cosmosdb.go
>  	for i := 0; i < 5; i++ {
Let's discuss on Teams

2022-09-26 22:05 UTC, jake-billings approved these changes

2022-09-27 17:13 UTC, julienstroheker commented on pkg/gencosmosdb/cosmosdb/cosmossdb_test.go
> +var _ = Describe("Testing Cosmos DB client utilities", func() {
Add UT when `errorString` is empty

Add UT when `errorString` contains multiple string

2022-09-27 17:15 UTC, julienstroheker commented on pkg/gencosmosdb/cosmosdb/cosmosdb.go
> +func IsErrorStatusMessage(err error, errorString string) bool {
This can be UT as well. Makes sure you are testing UPPERCASE and lowercase string as well

2022-09-27 17:17 UTC, julienstroheker commented on Makefile
> +	 ginkgo -r -v -trace -cover pkg
`ginkgo -r -v -trace -cover ./pkg/...`

2022-09-27 17:18 UTC, julienstroheker requested changes
Please check comments about UTs and makefile target

2022-09-27 18:54 UTC, julienstroheker approved these changes

2022-09-27 19:24 UTC, merged